spring:
  data:
    redis:
      password:
      cluster:
       max-redirects: 3
       nodes:
          127.0.0.1:7000,
          127.0.0.1:7001,
          127.0.0.1:7002,
          127.0.0.1:7003,
          127.0.0.1:7004,
          127.0.0.1:7005
      lettuce:
         pool:
           max-active: 8
           max-idle: 8
           min-idle: 0
           max-wait: -1ms

logging:
  level:
    io.lettuce.core: DEBUG
    org.springframework.data.redis: DEBUG
#    org.redisson.connection: DEBUG
    org.redisson.command: DEBUG